version: "3.9"

services:
  webapp:
    build:
      dockerfile: Dockerfile.dev
      context: ./packages/webapp
    ports:
      - 9230:9230
  core-service:
    build:
      dockerfile: Dockerfile.dev
      context: ./packages/core-service
    ports:
      - 9231:9231
    environment:
      NODE_OPTIONS: --inspect=0.0.0.0:9231
