version: "3.9"

services:
  postgres:
    image: postgres:14.5-alpine3.16
    restart: always
    ports:
    - 5432:5432
    volumes:
    - db_data:/var/lib/postgresql/data
    #- ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_PASSWORD: admin
  graphql-engine:
    image: hasura/graphql-engine:v2.12.0
    ports:
    - "8082:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:admin@postgres:5432/postgres
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:admin@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: admin
      HASURA_GRAPHQL_LOG_LEVEL: debug
  webapp:
    depends_on:
    - "postgres"
    - "graphql-engine"
    - "backend"
    ports:
    - 3000:3000
    build:
      context: packages/webapp
  backend:
    depends_on:
    - "postgres"
    - "graphql-engine"
    ports:
      - 3002:3002
    build:
      context: packages/backend
volumes:
  db_data:
    
