apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: webapp
build:
  artifacts:
  - image: skaffold-example
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - k8s-pod.yaml
